name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  #pull_request:
   # types:
    #  - closed

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1.6.0  # Use the latest version
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1.10.0  # Use the latest version
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image
      run: docker build -t draginojd/jensenstore:00 .