name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  #pull_request:
   # types:
    #  - closed

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.draginojd }}
        password: ${{ secrets.dckr_pat_MAquvXQNN9EHoWVLHvoljqYhdXg }}
    

    - name: Build and push Docker image
      run: docker build -t draginojd/jensenstore:00 .